name: awesome_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # 基础依赖
  # https://pub.flutter-io.cn/packages/provider
  provider: ^4.3.2+2
  # https://pub.flutter-io.cn/packages/device_info
  device_info: ^0.4.2+9
  # https://pub.flutter-io.cn/packages/package_info
  package_info: ^0.4.3
  # https://pub.flutter-io.cn/packages/dio
  dio: ^3.0.10
  # https://pub.flutter-io.cn/packages/path_provider
  path_provider: ^1.6.21
  # https://pub.flutter-io.cn/packages/oktoast
  oktoast: ^2.3.2
  # https://pub.flutter-io.cn/packages/pull_to_refresh
  pull_to_refresh: ^1.6.2
  # 谁用谁闪亮 (骨架屏) https://pub.flutter-io.cn/packages/shimmer
  shimmer: ^1.1.2
  # https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^5.7.5 #启动第三方app
  # https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: ^5.0.1+1
  #下方两个为常用工具类 详见文档：https://github.com/Sky24n/common_utils
  #适配、sp本地缓存、路径util等
  # https://pub.flutter-io.cn/packages/flustars
  flustars: ^0.3.3
  #字符串util、日期格式化、加解密、日志、等等
  # https://pub.flutter-io.cn/packages/common_utils
  common_utils: ^1.2.1
  # 本地json对象存储
  # https://pub.flutter-io.cn/packages/localstorage
  localstorage: ^3.0.3+6
  #https://github.com/fluttercandies/extended_image
  # https://pub.flutter-io.cn/packages/extended_image
  extended_image: ^1.3.0
  # https://pub.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^2.3.3
  # https://pub.flutter-io.cn/packages/extended_text
  extended_text: ^4.0.0
  # 网络状态 https://pub.flutter-io.cn/packages/connectivity
  connectivity: ^0.4.9+5
  #微信 mmkv 比sp更快
  # https://pub.flutter-io.cn/packages/mmkv_flutter
  mmkv_flutter: ^1.0.10
  # 基础依赖

  flutter_localizations:
    sdk: flutter
  rongcloud_im_plugin: ^4.0.1+5
  flutter_local_notifications: ^0.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/image/down.png
   - assets/image/up.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
